spring:
  datasource:
    url: jdbc:mysql://sh-cdb-ow7uekkj.sql.tencentcdb.com:63183/weibo?useUnicode=true&useSSL=false
    username: root
    password: recycle123
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      connection-init-sql: SET NAMES utf8mb4

  #jpa
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    database: mysql
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
  #重定向转发配置
  mvc:
    throw-exception-if-no-handler-found: true
    static-path-pattern: /**

###################################
############# REDIS
###################################
# Redis数据库索引
  redis:
    database: 0
# Redis服务器地址
    host: 127.0.0.1
# Redis服务器连接端口
    port: 6379
# 连接超时时间
    timeout: 5000ms